package entity;

public enum Language {
    ABKHAZ("Abkhaz"),
    ACEHNESE("Acehnese"),
    ACHOLI("Acholi"),
    AFRIKAANS("Afrikaans"),
    ALBANIAN("Albanian"),
    ALUR("Alur"),
    AMHARIC("Amharic"),
    ARABIC("Arabic"),
    ARMENIAN("Armenian"),
    ASSAMESE("Assamese"),
    AWADHI("Awadhi"),
    AYMARA("Aymara"),
    AZERBAIJANI("Azerbaijani"),
    BALINESE("Balinese"),
    BAMBARA("Bambara"),
    BASHKIR("Bashkir"),
    BASQUE("Basque"),
    BATAK("Batak"),
    BATAK_SIMALUNGUN("Batak Simalungun"),
    BATAK_TOBA("Batak Toba"),
    BELARUSIAN("Belarusian"),
    BEMBA("Bemba"),
    BENGALI("Bengali"),
    BETAWI("Betawi"),
    BHOJPURI("Bhojpuri"),
    BIKOL("Bikol"),
    BOSNIAN("Bosnian"),
    BRETON("Breton"),
    BULGARIAN("Bulgarian"),
    BURYAT("Buryat"),
    CANTONESE("Cantonese"),
    CATALAN("Catalan"),
    CEBUANO("Cebuano"),
    CHICHEWA("Chichewa (Nyanja)"),
    CHINESE_SIMPLIFIED("Chinese (Simplified)"),
    CHINESE_TRADITIONAL("Chinese (Traditional)"),
    CHUVASH("Chuvash"),
    CORSICAN("Corsican"),
    CRIMEAN_TATAR("Crimean Tatar"),
    CROATIAN("Croatian"),
    CZECH("Czech"),
    DANISH("Danish"),
    DINKA("Dinka"),
    DIVEHI("Divehi"),
    DOGRI("Dogri"),
    DOMBE("Dombe"),
    DUTCH("Dutch"),
    DZONGKHA("Dzongkha"),
    ENGLISH("English"),
    ESPERANTO("Esperanto"),
    ESTONIAN("Estonian"),
    EWE("Ewe"),
    FIJIAN("Fijian"),
    FILIPINO_TAGALOG("Filipino (Tagalog)"),
    FINNISH("Finnish"),
    FRENCH("French"),
    FRENCH_FRANCE("French (France)"),
    FRENCH_CANADIAN("French (Canadian)"),
    FRISIAN("Frisian"),
    FULFULDE("Fulfulde"),
    GA("Ga"),
    GALICIAN("Galician"),
    GANDA("Ganda (Luganda)"),
    GEORGIAN("Georgian"),
    GERMAN("German"),
    GREEK("Greek"),
    GUARANI("Guarani"),
    GUJARATI("Gujarati"),
    HAITIAN_CREOLE("Haitian Creole"),
    HAKHA_CHIN("Hakha Chin"),
    HAUSA("Hausa"),
    HAWAIIAN("Hawaiian"),
    HEBREW("Hebrew"),
    HILIGAYNON("Hiligaynon"),
    HINDI("Hindi"),
    HMONG("Hmong"),
    HUNGARIAN("Hungarian"),
    HUNSRIK("Hunsrik"),
    ICELANDIC("Icelandic"),
    IGBO("Igbo"),
    ILOKO("Iloko"),
    INDONESIAN("Indonesian"),
    IRISH("Irish"),
    ITALIAN("Italian"),
    JAPANESE("Japanese"),
    JAVANESE("Javanese"),
    KANNADA("Kannada"),
    KAPAMPANGAN("Kapampangan"),
    KAZAKH("Kazakh"),
    KHMER("Khmer"),
    KIGA("Kiga"),
    KINYARWANDA("Kinyarwanda"),
    KITUBA("Kituba"),
    KONKANI("Konkani"),
    KOREAN("Korean"),
    KRIO("Krio"),
    KURDISH_KURMANJI("Kurdish (Kurmanji)"),
    KURDISH_SORANI("Kurdish (Sorani)"),
    KYRGYZ("Kyrgyz"),
    LAO("Lao"),
    LATGALIAN("Latgalian"),
    LATIN("Latin"),
    LATVIAN("Latvian"),
    LIGURIAN("Ligurian"),
    LIMBURGAN("Limburgan"),
    LINGALA("Lingala"),
    LITHUANIAN("Lithuanian"),
    LOMBARD("Lombard"),
    LUO("Luo"),
    LUXEMBOURGISH("Luxembourgish"),
    MACEDONIAN("Macedonian"),
    MAITHILI("Maithili"),
    MAKASSAR("Makassar"),
    MALAGASY("Malagasy"),
    MALAY("Malay"),
    MALAY_JAWI("Malay (Jawi)"),
    MALAYALAM("Malayalam"),
    MALTESE("Maltese"),
    MAORI("Maori"),
    MARATHI("Marathi"),
    MEADOW_MARI("Meadow Mari"),
    MEITEILON("Meiteilon (Manipuri)"),
    MINANG("Minang"),
    MIZO("Mizo"),
    MONGOLIAN("Mongolian"),
    MYANMAR_BURMESE("Myanmar (Burmese)"),
    NDEBELE_SOUTH("Ndebele (South)"),
    NEPALBHASA("Nepalbhasa (Newari)"),
    NEPALI("Nepali"),
    NORTHERN_SOTHO("Northern Sotho (Sepedi)"),
    NORWEGIAN("Norwegian"),
    NUER("Nuer"),
    OCCITAN("Occitan"),
    ODIA("Odia (Oriya)"),
    OROMO("Oromo"),
    PANGASINAN("Pangasinan"),
    PAPIAMENTO("Papiamento"),
    PASHTO("Pashto"),
    PERSIAN("Persian"),
    POLISH("Polish"),
    PORTUGUESE("Portuguese"),
    PORTUGUESE_PORTUGAL("Portuguese (Portugal)"),
    PORTUGUESE_BRAZIL("Portuguese (Brazil)"),
    PUNJABI("Punjabi"),
    PUNJABI_SHAHMUKHI("Punjabi (Shahmukhi)"),
    QUECHUA("Quechua"),
    ROMANI("Romani"),
    ROMANIAN("Romanian"),
    RUNDI("Rundi"),
    RUSSIAN("Russian"),
    SAMOAN("Samoan"),
    SANGO("Sango"),
    SANSKRIT("Sanskrit"),
    SCOTS_GAELIC("Scots Gaelic"),
    SERBIAN("Serbian"),
    SESOTHO("Sesotho"),
    SEYCHELLOIS_CREOLE("Seychellois Creole"),
    SHAN("Shan"),
    SHONA("Shona"),
    SICILIAN("Sicilian"),
    SILESIAN("Silesian"),
    SINDHI("Sindhi"),
    SINHALA("Sinhala (Sinhalese)"),
    SLOVAK("Slovak"),
    SLOVENIAN("Slovenian"),
    SOMALI("Somali"),
    SPANISH("Spanish"),
    SUNDANESE("Sundanese"),
    SWAHILI("Swahili"),
    SWATI("Swati"),
    SWEDISH("Swedish"),
    TAJIK("Tajik"),
    TAMIL("Tamil"),
    TATAR("Tatar"),
    TELUGU("Telugu"),
    TETUM("Tetum"),
    THAI("Thai"),
    TIGRINYA("Tigrinya"),
    TSONGA("Tsonga"),
    TSWANA("Tswana"),
    TURKISH("Turkish"),
    TURKMEN("Turkmen"),
    TWI_AKAN("Twi (Akan)"),
    UKRAINIAN("Ukrainian"),
    URDU("Urdu"),
    UYGHUR("Uyghur"),
    UZBEK("Uzbek"),
    VIETNAMESE("Vietnamese"),
    WELSH("Welsh"),
    XHOSA("Xhosa"),
    YIDDISH("Yiddish"),
    YORUBA("Yoruba"),
    YUCATEC_MAYA("Yucatec Maya"),
    ZULU("Zulu");

    private final String displayName;

    Language(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }

    @Override
    public String toString() {
        return displayName;
    }
}